### ISSUE TITLE
Error: Failed to install 'pfGO' from GitHub:

### ISSUE THREAD

**Issue by Rohit-Satyam** [oberstal/pfGO#13]
Hi @oberstal 

I was trying to install your package but I got this error. Can you see what's causing it?

```
> devtools::install_github("oberstal/pfGO")
Downloading GitHub repo oberstal/pfGO@HEAD
Error: Failed to install 'pfGO' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/GO.db RELEASE_3_18 2>/dev/null' had status 128
```

PS: Are you developing this for your day-to-day analysis or do you intend to expand this package's functionality? If you would like to collaborate please let me know.

**Comment by oberstal** [comment]
hi @Rohit-Satyam 
Sorry I missed your issue and thanks for reporting it. The error should be resolved now in release 2.1.0.

I update this package periodically/as needed mostly as it relates to my own research. I'm always thinking of adding to it but it unfortunately tends to get back-burnered for funded projects. I am happy to consider further development/take suggestions as I'm able if others find it useful!
